spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.22:///doesntmatter/ignored
    username: dummy
    password: dummy
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/testdata
  jpa:
    hibernate:
      ddl-auto: none
